DROP TABLE IF EXISTS adresses CASCADE;
DROP TABLE IF EXISTS clients CASCADE;

CREATE TABLE "clients" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(120)
);

CREATE TABLE "adresses" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(150) NOT NULL,
    house VARCHAR(20) NOT NULL,
    appartments INTEGER,
    floor INTEGER,
    entrance INTEGER,
    client_id BIGINT NOT NULL,
    CONSTRAINT fk_address_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE
);

CREATE TABLE "dishes" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight_volume VARCHAR(60) NOT NULL,
    image_url VARCHAR(300),
    name VARCHAR(150) NOT NULL,
    price INTEGER,
    is_active BOOLEAN NOT NULL,
    description TEXT,
    -- category_id INTEGER NOT NULL REFERENCES category(id) ON DELETE RESTRICT
);